# version: '3.8'

services:
  sleek-airflow:
    build: 
      context: .  # This should point to the directory containing the Dockerfile
      dockerfile: Dockerfile # Optional if the file is named Dockerfile
    image: sleek-airflow:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone